services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=chatter_admin
      - POSTGRES_PASSWORD=chatter_adminPW1!
      - POSTGRES_DB=chatter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init-scripts/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      interval: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chatter
      - SPRING_DATASOURCE_USERNAME=chatter_admin
      - SPRING_DATASOURCE_PASSWORD=chatter_adminPW1!

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
